/* SERENDIPPO-LIDAR-VIEWER — Configuration globale */

LV.CONFIG = Object.freeze({
  // Vue par defaut : Puy de Dôme (volcan, LiDAR spectaculaire)
  defaultView: { lat: 45.7725, lng: 2.9648, zoom: 14 },
  defaultRight: 'hybrid',
  leftKey: 'lidar',
  sbsMin: 2,
  sbsMax: 98,

  bookmarks: [
    // ── France - LiDAR démonstration (relief, structures) ──
    { id: 'puydedome',  name: 'Puy de Dome',              lat: 45.7725, lng: 2.9648,  zoom: 14, notes: 'Volcan auvergnat, LiDAR remarquable' },
    { id: 'metz',       name: 'Metz - Base aerienne',     lat: 49.1341, lng: 6.1239,  zoom: 16, notes: 'Base aerienne 128, nord-est Moselle' },
    { id: 'eiffel',     name: 'Tour Eiffel',              lat: 48.8584, lng: 2.2945,  zoom: 17, notes: 'Monument parisien, structure metallique' },
    { id: 'versailles', name: 'Chateau de Versailles',     lat: 48.8049, lng: 2.1204,  zoom: 16, notes: 'Parc et jardins a la francaise' },
    { id: 'chambord',   name: 'Chateau de Chambord',      lat: 47.6161, lng: 1.5169,  zoom: 16, notes: 'Foret de Sologne, architecture Renaissance' },
    { id: 'carcassonne',name: 'Cite de Carcassonne',      lat: 43.2060, lng: 2.3630,  zoom: 16, notes: 'Forteresse medievale' },
    { id: 'pontdugard', name: 'Pont du Gard',             lat: 43.9475, lng: 4.5350,  zoom: 16, notes: 'Aqueduc romain, vallee du Gardon' },
    { id: 'millau',     name: 'Viaduc de Millau',         lat: 44.0778, lng: 3.0228,  zoom: 15, notes: 'Ouvrage d art, canyon du Tarn' },
    { id: 'montblanc',  name: 'Mont Blanc',               lat: 45.8326, lng: 6.8652,  zoom: 13, notes: 'Toit de l Europe, relief alpin' },
    { id: 'gavarnie',   name: 'Cirque de Gavarnie',       lat: 42.7344, lng: -0.0096, zoom: 14, notes: 'Cirque glaciaire pyreneen' },
    { id: 'verdon',     name: 'Gorges du Verdon',         lat: 43.7372, lng: 6.3639,  zoom: 13, notes: 'Canyon profond, relief spectaculaire' },
    { id: 'etretat',    name: 'Falaises d Etretat',       lat: 49.7083, lng: 0.2042,  zoom: 15, notes: 'Arches et falaises de craie normandes' },
    { id: 'pilat',      name: 'Dune du Pilat',            lat: 44.5892, lng: -1.2133, zoom: 15, notes: 'Plus haute dune d Europe, foret et ocean' },
    { id: 'calanques',  name: 'Calanques de Marseille',   lat: 43.2108, lng: 5.4483,  zoom: 14, notes: 'Cretes calcaires et criques mediterraneennes' },
    { id: 'msm',        name: 'Mont-Saint-Michel',        lat: 48.6360, lng: -1.5114, zoom: 14, notes: 'Baie et abbaye (ortho seulement, pas LiDAR)' },
    { id: 'ventoux',    name: 'Mont Ventoux',             lat: 44.1741, lng: 5.2787,  zoom: 13, notes: 'Giant de Provence, relief karstique' },
    { id: 'salagou',    name: 'Lac du Salagou',           lat: 43.6542, lng: 3.3858,  zoom: 14, notes: 'Lac rouge, collines et terroirs languedociens' },
    { id: 'carnac',     name: 'Alignements de Carnac',    lat: 47.5958, lng: -3.0817, zoom: 15, notes: 'Megalithes neolithiques visibles en LiDAR' },
    { id: 'rennes',     name: 'Rennes-le-Chateau',        lat: 42.9276, lng: 2.2605,  zoom: 16, notes: 'Site mysterieux, pays cathare' },

    // ── France - Patrimoine, archeologie et paysages ──
    { id: 'oradour',        name: 'Oradour-sur-Glane',          lat: 45.9305, lng: 1.0338, zoom: 16, notes: 'Village martyr, ruines preservees' },
    { id: 'douaumont',      name: 'Fort de Douaumont',          lat: 49.2203, lng: 5.4346, zoom: 15, notes: 'Fort de la Premiere Guerre mondiale' },
    { id: 'vaux',           name: 'Fort de Vaux',               lat: 49.2136, lng: 5.4492, zoom: 16, notes: 'Fort de la Premiere Guerre mondiale' },
    { id: 'ossuaire',       name: 'Ossuaire de Douaumont',      lat: 49.2168, lng: 5.4165, zoom: 16, notes: 'Memorial de la Grande Guerre' },
    { id: 'bibracte',       name: 'Oppidum de Bibracte',        lat: 46.9239, lng: 4.0369, zoom: 14, notes: 'Oppidum gaulois, Mont Beuvray' },
    { id: 'beuvray',        name: 'Mont Beuvray',               lat: 46.9231, lng: 4.0363, zoom: 14, notes: 'Sommet du Morvan, site archeologique' },
    { id: 'montsegur',      name: 'Chateau de Montsegur',       lat: 42.8715, lng: 1.8338, zoom: 16, notes: 'Chateau cathare sur un piton rocheux' },
    { id: 'nimes',          name: 'Arenes de Nimes',            lat: 43.8366, lng: 4.3601, zoom: 17, notes: 'Amphitheatre romain' },
    { id: 'orange',         name: 'Theatre antique d Orange',   lat: 44.1368, lng: 4.8083, zoom: 17, notes: 'Theatre romain, patrimoine UNESCO' },
    { id: 'enserune',       name: 'Oppidum d Enserune',         lat: 43.2807, lng: 3.1227, zoom: 15, notes: 'Oppidum gaulois, vue sur l Etang de Thau' },
    { id: 'alesia',         name: 'Alesia',                     lat: 47.5366, lng: 4.4958, zoom: 14, notes: 'Site du siege d Alesia, vestiges gaulois' },
    { id: 'jumieges',       name: 'Abbaye de Jumieges',         lat: 49.4272, lng: 0.8202, zoom: 16, notes: 'Abbaye romane en ruine, boucle de Seine' },
    { id: 'arcetsenans',    name: 'Saline d Arc-et-Senans',     lat: 47.0326, lng: 5.7786, zoom: 16, notes: 'Saline royale, architecture industrielle' },
    { id: 'bruoux',         name: 'Mines de Bruoux',            lat: 43.8780, lng: 5.3966, zoom: 16, notes: 'anciennes mines d ocre, sentiers' },
    { id: 'wellington',     name: 'Carriere Wellington',        lat: 50.2877, lng: 2.7770, zoom: 17, notes: 'Carriere souterraine, Premiere Guerre' },
    { id: 'cluny',          name: 'Abbaye de Cluny',            lat: 46.4337, lng: 4.6594, zoom: 16, notes: 'Abbaye benedictine, plus grande eglise medievale' },
    { id: 'rocamadour',     name: 'Rocamadour',                 lat: 44.7998, lng: 1.6170, zoom: 16, notes: 'Cite suspendue, vallee de l Alzou' },
    { id: 'montpellierlv',  name: 'Chaos de Montpellier-le-Vieux', lat: 44.2008, lng: 3.2285, zoom: 14, notes: 'Chaos rocheux, dolomies du Causse Noir' },
    { id: 'gergovie',       name: 'Plateau de Gergovie',        lat: 45.7114, lng: 3.1380, zoom: 15, notes: 'Plateau de la bataille de Gergovie' },
    { id: 'rocheauxfees',   name: 'Dolmen de la Roche-aux-Fees', lat: 47.9368, lng: -1.3663, zoom: 16, notes: 'Dolmen neolithique, Ille-et-Vilaine' },
    { id: 'uxellodunum',    name: 'Oppidum d Uxellodunum',      lat: 44.6360, lng: 1.7828, zoom: 15, notes: 'Dernier oppidum gaulois, siege de Cesar' },
    { id: 'sainteodile',    name: 'Mont Sainte-Odile',          lat: 48.4334, lng: 7.4015, zoom: 15, notes: 'Monastere, mur paien, vue sur Alsace' },
    { id: 'padirac',        name: 'Gouffre de Padirac',         lat: 44.8465, lng: 1.7534, zoom: 16, notes: 'Gouffre et riviere souterraine, Quercy' },

    // ── Vauban - Fortifications (remarquables en LiDAR) ──
    { id: 'vauban_arras',       name: 'Citadelle d Arras',              lat: 50.2825, lng: 2.7589, zoom: 16, notes: 'Vauban - Citadelle, place forte du Nord' },
    { id: 'vauban_besancon',    name: 'Citadelle de Besancon',          lat: 47.2361, lng: 6.0277, zoom: 16, notes: 'Vauban - UNESCO, boucle du Doubs' },
    { id: 'vauban_blaye',       name: 'Citadelle de Blaye',            lat: 45.1272, lng: -0.6747, zoom: 16, notes: 'Vauban - Verrou de l estuaire Girondin' },
    { id: 'vauban_medoc',       name: 'Fort Medoc',                    lat: 45.1061, lng: -0.7355, zoom: 16, notes: 'Vauban - Fort de l estuaire' },
    { id: 'vauban_pate',        name: 'Fort Pate',                    lat: 45.1517, lng: -0.6547, zoom: 16, notes: 'Vauban - Fort de l estuaire' },
    { id: 'vauban_briancon',    name: 'Citadelle de Briancon',         lat: 44.8992, lng: 6.6436, zoom: 16, notes: 'Vauban - UNESCO, place forte des Alpes' },
    { id: 'vauban_troistetes',  name: 'Fort des Trois-Tetes',          lat: 44.9028, lng: 6.6554, zoom: 16, notes: 'Vauban - Briancon' },
    { id: 'vauban_randouillet', name: 'Fort du Randouillet',           lat: 44.9120, lng: 6.6508, zoom: 16, notes: 'Vauban - Briancon' },
    { id: 'vauban_salettes',    name: 'Fort des Salettes',             lat: 44.9029, lng: 6.6398, zoom: 16, notes: 'Vauban - Briancon' },
    { id: 'vauban_montlouis',   name: 'Citadelle de Mont-Louis',       lat: 42.5085, lng: 2.1205, zoom: 16, notes: 'Vauban - UNESCO, plus haute citadelle' },
    { id: 'vauban_neufbrisach', name: 'Neuf-Brisach',                  lat: 48.0178, lng: 7.5278, zoom: 15, notes: 'Vauban - UNESCO, ville en etoile' },
    { id: 'vauban_saintmartin', name: 'Citadelle de Saint-Martin-de-Re', lat: 46.2034, lng: -1.3662, zoom: 16, notes: 'Vauban - UNESCO, ile de Re' },
    { id: 'vauban_lille',       name: 'Citadelle de Lille',            lat: 50.6396, lng: 3.0348, zoom: 16, notes: 'Vauban - Reine des citadelles' },
    { id: 'vauban_quesnoy',     name: 'Citadelle de Le Quesnoy',      lat: 50.2478, lng: 3.6372, zoom: 16, notes: 'Vauban - Place forte du Nord' },
    { id: 'vauban_maubeuge',    name: 'Fortifications de Maubeuge',    lat: 50.2789, lng: 3.9734, zoom: 16, notes: 'Vauban - Place forte' },
    { id: 'vauban_longwy',      name: 'Citadelle de Longwy',           lat: 49.5231, lng: 5.7618, zoom: 16, notes: 'Vauban - UNESCO, place forte du Nord-Est' },
    { id: 'vauban_belfort',     name: 'Citadelle de Belfort',          lat: 47.6380, lng: 6.8565, zoom: 16, notes: 'Vauban - Place forte, Lion de Belfort' },
    { id: 'vauban_joux',        name: 'Chateau de Joux',              lat: 46.8706, lng: 6.3728, zoom: 16, notes: 'Vauban - Fortifie par Vauban, Jura' },
    { id: 'vauban_liberia',     name: 'Fort Liberia',                 lat: 42.5887, lng: 2.3689, zoom: 16, notes: 'Vauban - Villefranche-de-Conflent' },
    { id: 'vauban_bellegarde',  name: 'Fort de Bellegarde',           lat: 42.4606, lng: 2.8578, zoom: 16, notes: 'Vauban - Col du Perthus' },
    { id: 'vauban_lagarde',     name: 'Fort Lagarde',                 lat: 42.4049, lng: 2.4795, zoom: 16, notes: 'Vauban - Prats-de-Mollo' },
    { id: 'vauban_perpignan',   name: 'Citadelle de Perpignan',       lat: 42.6954, lng: 2.8987, zoom: 16, notes: 'Vauban - Chateau royal' },
    { id: 'vauban_standre',     name: 'Fort Saint-Andre',             lat: 43.9665, lng: 4.7945, zoom: 16, notes: 'Vauban - Villeneuve-les-Avignon' },
    { id: 'vauban_antibes',     name: 'Fort Carre Antibes',           lat: 43.5867, lng: 7.1268, zoom: 16, notes: 'Vauban - Fortifie par Vauban' },
    { id: 'vauban_marguerite',  name: 'Fort de Sainte-Marguerite',    lat: 43.5227, lng: 7.0432, zoom: 16, notes: 'Vauban - Iles de Lerins, Cannes' },
    { id: 'vauban_bouc',        name: 'Fort de Bouc',                lat: 43.4050, lng: 4.9830, zoom: 16, notes: 'Vauban - Bouches-du-Rhone' },
    { id: 'vauban_portlouis',   name: 'Citadelle de Port-Louis',      lat: 47.7062, lng: -3.3539, zoom: 16, notes: 'Vauban - Place forte bretonne' },
    { id: 'vauban_lupin',       name: 'Fort Lupin',                  lat: 45.9598, lng: -1.0157, zoom: 16, notes: 'Vauban - Fort cotier' },
    { id: 'vauban_chapus',      name: 'Fort Chapus',                 lat: 45.8538, lng: -1.1954, zoom: 16, notes: 'Vauban - Fort cotier' },
    { id: 'vauban_boyard',      name: 'Fort Boyard',                 lat: 45.9990, lng: -1.2130, zoom: 16, notes: 'Vauban - Inspiration Vauban' },
    { id: 'vauban_camaret',     name: 'Tour Vauban Camaret',          lat: 48.2746, lng: -4.5960, zoom: 16, notes: 'Vauban - UNESCO, tour cotiere' },
    { id: 'vauban_conchee',     name: 'Fort de la Conchee',          lat: 48.6772, lng: -2.0065, zoom: 16, notes: 'Vauban - Saint-Malo' },
    { id: 'vauban_national',    name: 'Fort National Saint-Malo',     lat: 48.6516, lng: -2.0230, zoom: 16, notes: 'Vauban - Saint-Malo' },
    { id: 'vauban_bayonne',     name: 'Citadelle de Bayonne',         lat: 43.4945, lng: -1.4706, zoom: 16, notes: 'Vauban - Place forte du Sud-Ouest' },
    { id: 'vauban_stjeanpied',  name: 'Citadelle de Saint-Jean-Pied-de-Port', lat: 43.1635, lng: -1.2377, zoom: 16, notes: 'Vauban - Pays basque' },
    { id: 'vauban_calais',      name: 'Citadelle de Calais',          lat: 50.9554, lng: 1.8434, zoom: 16, notes: 'Vauban - Place forte du Nord' },
    { id: 'vauban_dunkerque',   name: 'Citadelle de Dunkerque',       lat: 51.0374, lng: 2.3774, zoom: 16, notes: 'Vauban - Place forte' },
    { id: 'vauban_fortlouis',   name: 'Fort-Louis',                  lat: 48.7994, lng: 8.0588, zoom: 16, notes: 'Vauban - Alsace' },
    { id: 'vauban_bitche',      name: 'Citadelle de Bitche',          lat: 49.0516, lng: 7.4266, zoom: 16, notes: 'Vauban - Place forte des Vosges' },
    { id: 'vauban_rocroi',      name: 'Place forte de Rocroi',       lat: 49.9269, lng: 4.5225, zoom: 15, notes: 'Vauban - Ville en etoile, Ardennes' },
    { id: 'vauban_givet',       name: 'Place forte de Givet',        lat: 50.1357, lng: 4.8230, zoom: 16, notes: 'Vauban - Charlemont, Ardennes' },
    { id: 'vauban_montdauphin', name: 'Place forte de Mont-Dauphin',  lat: 44.6672, lng: 6.6210, zoom: 15, notes: 'Vauban - UNESCO, Alpes' },
    { id: 'vauban_entrevaux',   name: 'Place forte d Entrevaux',     lat: 43.9474, lng: 6.8105, zoom: 16, notes: 'Vauban - Alpes-de-Haute-Provence' },
    { id: 'vauban_colmars',     name: 'Place forte de Colmars',      lat: 44.1814, lng: 6.6307, zoom: 16, notes: 'Vauban - Alpes-de-Haute-Provence' },

    // ── Espagne ──
    { id: 'barcelona',  name: 'Barcelone - Sagrada Familia',  lat: 41.4036, lng: 2.1744,  zoom: 16, notes: 'LiDAR PNOA Espagne, MTN historique' },
    { id: 'madrid',     name: 'Madrid - Centro',              lat: 40.4168, lng: -3.7038, zoom: 15, notes: 'MDT et cartes anciennes IGN Espagne' },
    { id: 'granada',    name: 'Grenade - Alhambra',           lat: 37.1760, lng: -3.5886, zoom: 16, notes: 'Relief andalou, LiDAR IDEe' },

    // ── Italie ──
    { id: 'rome',       name: 'Rome - Colisee',               lat: 41.8902, lng: 12.4922, zoom: 16, notes: 'LiDAR PCN Latium, IGM 1:25 000' },
    { id: 'florence',   name: 'Florence - Duomo',             lat: 43.7731, lng: 11.2560, zoom: 16, notes: 'LiDAR PCN Toscane, TINITALY' },
    { id: 'venice',     name: 'Venise - Piazza San Marco',    lat: 45.4340, lng: 12.3380, zoom: 16, notes: 'LiDAR PCN Veneto, lagune' },
    { id: 'milan',      name: 'Milan - Duomo',                lat: 45.4642, lng: 9.1900,  zoom: 16, notes: 'LiDAR PCN Lombardie/Piemont' },
    { id: 'roma_lidar', name: 'Rome - Test LiDAR',            lat: 41.8979, lng: 12.4766, zoom: 15, notes: 'LiDAR PCN Latium 2m - DTM test' },
    { id: 'napoli',     name: 'Naples - Vesuve',              lat: 40.8264, lng: 14.3050, zoom: 14, notes: 'LiDAR Campanie - DTM 2m' },
    { id: 'etna',       name: 'Etna - Sicile',                lat: 37.7510, lng: 14.9934, zoom: 13, notes: 'LiDAR Sicile - relief volcanique' },
  ]
});